#ifndef __MINSTL_ENDIAN_H
#define __MINSTL_ENDIAN_H

#define __LITTLE_ENDIAN __ORDER_LITTLE_ENDIAN__
#define __BIG_ENDIAN    __ORDER_BIG_ENDIAN__
#define __PDP_ENDIAN    __ORDER_PDP_ENDIAN__
#define __BYTE_ORDER    __BYTE_ORDER__

#define LITTLE_ENDIAN   __ORDER_LITTLE_ENDIAN__
#define BIG_ENDIAN      __ORDER_BIG_ENDIAN__
#define PDP_ENDIAN      __ORDER_PDP_ENDIAN__
#define BYTE_ORDER      __BYTE_ORDER__


#endif // __MINSTL_ENDIAN_H
